### ISSUE TITLE
[zig 0.14.0-dev] fails to compile: no field named 'Pointer' in enum

### ISSUE THREAD

**Issue by doums** [chrischtel/nexlog#24]
Hi, first thx you for the lib, it looks promising.
Second, I'm new in zig so it is possible that the issue is on me.
I'm playing around, and I just tried to add your lib as a dependency of my simple zig exe project.

I zfetched using `develop` branch, and that's what I put in my `build.zig`

```zig
  […]

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "tarse",
        .root_module = exe_mod,
    });

    // nexlog
    const nexlog = b.dependency("nexlog", .{
        .target = target,
        .optimize = optimize,
    });
    exe.root_module.addImport("nexlog", nexlog.module("nexlog"));
```

Then trying to setup the logger in `main.zig`

```zig
const std = @import("std");
const nexlog = @import("nexlog");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();

    const allocator = arena.allocator();

    var builder = nexlog.LogBuilder.init();
    try builder
        .setMinLevel(.debug)
        .enableColors(true)
        .setBufferSize(4096)
        .enableFileLogging(false, null)
        .enableMetadata(true)
        .build(allocator);
    defer nexlog.deinit();
    const logger = nexlog.getDefaultLogger() orelse return error.LoggerNotInitialized;

    const metadata = nexlog.LogMetadata{
        .timestamp = std.time.timestamp(),
        .thread_id = 0,
        .file = @src().file,
        .line = @src().line,
        .function = @src().fn_name,
    };

    try logger.log(.info, "Hello", .{}, metadata);
}
```

But when I try to `zig build`, I get the following error:

```
›  ~/D/s/tarse zig build
install
└─ install tarse
   └─ zig build-exe tarse Debug native 2 errors
/home/pierre/.cache/zig/p/122006080c9f00c8b10d2fdb98e3a63b7c0cbffd3e3c1fb866aae80269d8d3ec0866/src/output/handlers.zig:38:39: error: no field named 'Pointer' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
        std.debug.assert(ptr_info == .Pointer); // Must be a pointer
                                     ~^~~~~~~
/usr/lib/zig/lib/std/builtin.zig:557:18: note: enum declared here
pub const Type = union(enum) {
                 ^~~~~
referenced by:
    toLogHandler: /home/pierre/.cache/zig/p/122006080c9f00c8b10d2fdb98e3a63b7c0cbffd3e3c1fb866aae80269d8d3ec0866/src/output/console.zig:69:40
    init: /home/pierre/.cache/zig/p/122006080c9f00c8b10d2fdb98e3a63b7c0cbffd3e3c1fb866aae80269d8d3ec0866/src/core/logger.zig:44:63
    9 reference(s) hidden; use '-freference-trace=11' to see all references
/home/pierre/.cache/zig/p/122006080c9f00c8b10d2fdb98e3a63b7c0cbffd3e3c1fb866aae80269d8d3ec0866/src/output/handlers.zig:38:39: error: no field named 'Pointer' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
        std.debug.assert(ptr_info == .Pointer); // Must be a pointer
                                     ~^~~~~~~
/usr/lib/zig/lib/std/builtin.zig:557:18: note: enum declared here
pub const Type = union(enum) {
                 ^~~~~
error: the following command failed with 2 compilation errors:
/usr/lib/zig/zig build-exe -ODebug --dep nexlog -Mroot=/home/pierre/Documents/scrap/tarse/src/main.zig -Mnexlog=/home/pierre/.cache/zig/p/122006080c9f00c8b10d2fdb98e3a63b7c0cbffd3e3c1fb866aae80269d8d3ec0866/src/nexlog.zig --cache-dir /home/pierre/Documents/scrap/tarse/.zig-cache --global-cache-dir /home/pierre/.cache/zig --name tarse --zig-lib-dir /usr/lib/zig/lib/ --listen=-
Build Summary: 0/3 steps succeeded; 1 failed
install transitive failure
└─ install tarse transitive failure
   └─ zig build-exe tarse Debug native 2 errors
error: the following build command failed with exit code 1:
/home/pierre/Documents/scrap/tarse/.zig-cache/o/fd6994ee3dc523e51a447d9f1fa0f6e5/build /usr/lib/zig/zig /usr/lib/zig/lib /home/pierre/Documents/scrap/tarse /home/pierre/Documents/scrap/tarse/.zig-cache /home/pierre/.cache/zig --seed 0x501d57e0 -Z10fff5a6dc19954c
```

NOTE: I'm using zig `0.14.0-dev.2623+7aa95bc7f`

**Comment by doums** [comment]
Actually, I tried to build nexlog from source and on both branch it failed with a lot of errors including bunch of `no field named 'Pointer' in enum` errors.
I guess I find the answer, nexlog is not yet compatible with zig 0.14 dev.

**Comment by chrischtel** [comment]
Hi @doums,

Thank you for giving my library a try! Currently, it only supports the latest stable release of Zig (v0.13), so it won't work with 0.14.x-dev. Since I'm still relatively new to Zig, it's easier for me to target the stable branch for now. That said, I plan to look into updating the library for the latest dev branch in the future.

I'm also working on implementing custom formatting, though that part is still a work in progress. I might set it aside temporarily to focus on adding support for v0.14.

Thanks again for your interest and understanding!

**Comment by chrischtel** [comment]
Hey quick update, I actually fixed it by replacing two capital letters with their corresponding lower case letters. 
You can add the current stable-ish version with support for v0.14-x using (I tested for `0.14.0-dev.3026+c225b780e`)

`zig fetch --save https://github.com/chrischtel/nexlog/archive/refs/tags/v0.2.0-rc.2.tar.gz`

Please note that the format functionality is more or less broken... but in general most of the normal logging features are stable.
Have fun trying out `nexlog` and if you catch more bugs, just create an issue.

Thank you very much,
Christian

**Comment by doums** [comment]
Hi @chrischtel thx for the 0.14-dev support, that is really cool!
Tbh when I figured out that 0.14-dev was not (yet) supported I switched to [logz](https://github.com/karlseguin/log.zig), which worked out of the box.
But I'll retry nexlog for sure, especially since I find colorized output very valuable when it comes for logging to stdout.

Nevertheless, I already can give you those feedbacks:

1. call API and level
I find the basic usage API a bit harsh to use

```zig
try logger.log(.info, "some ctx {s}", .{"value"}, metadata);
try logger.log(.error, "some ctx {s}", .{"value"}, metadata);
```

it would be better (shorter so simpler) to exposed it like

```zig
try logger.info("some ctx {s}", .{"value"}, metadata);
try logger.error("some ctx {s}", .{"value"}, metadata);
// etc
```
Using `log(Level ...` is redundant because, at least as a default API usage, we will always call `log` method followed by the Level. So why not simplifying the call?

2. make it infallible so more programmer friendly

So for this one, it will depend on the reason(s) why you exposed the call API as “fallible” so returning an error union type.
But for such a general purpose API, I would absolutely opt for a non-fallible one: as a programmer I want the logger I use to be 100% reliable and I don't want to have to deal with potential errors each time I'm using it!

```zig
logger.info("some ctx {s}", .{"value"}, metadata); // no need to `try` or `catch` this call is safe
```

**Comment by chrischtel** [comment]
Hi, thanks a lot for your feedback, I really appreciate it.

Of course, you can stay on logz until I figure things out—I still need to find a branching solution and sort everything out.

But thanks again! I’ll adjust these as quickly as possible, as I’m not really in a proper workflow or release cycle yet.

**Comment by chrischtel** [comment]
Hey @doums I implemented your suggestions, great ideas, thanks for that.
You can now use e.g `logger.info("some ctx {s}", .{"value"}, metadata);`

I am currently also thinking of refactoring the metadata, I thought of adding a way to submit the meta once and not always needing to pass it over to the log function. What would you think of it?

**Comment by doums** [comment]
Wow, awesome! Once I get some time (currently mainly working with Rust & TS for day job)  I'll try out!

> I am currently also thinking of refactoring the metadata, I thought of adding a way to submit the meta once and not always needing to pass it over to the log function. What would you think of it?

100% agree ;) (same approach logz chose for its api too).
Once this is implemented, I think it will be the near perfect default API for nexlog!
